service: default
runtime: python38

env_variables:
  TMPDIR: "/my/path"
#    GAE_MEMORY_MB: 5000

basic_scaling:
    max_instances: 1
    idle_timeout: 20m

default_expiration: "4d 5h"

instance_class: B8

entrypoint: gunicorn -b :$PORT main:server  --timeout 0 --graceful-timeout 1200
