service: default
runtime: python38

env_variables:
  TMPDIR: "/tmp"
#    GAE_MEMORY_MB: 5000

#automatic_scaling:


default_expiration: "4d 5h"

inbound_services:
- warmup

handlers:
- url: /_ah/warmup
  script: main.py

instance_class: F4

entrypoint: gunicorn -b :$PORT main:server  --timeout 0 --graceful-timeout 1200
